# .schema.yaml

# Define input, output and source for $refs relative to repository root for pre-commit
values:
  - Charts/fastcs/service.values.yaml

output: Charts/fastcs/service.values.schema.json


# bundle up references (don't do this as K8S refs are 500kb+)
bundleRoot: Charts
bundle: false

# Include comments for the helm-docs plugin into the schema, to allow e.g. documentation in VSCode
useHelmDocs: false

# Allow additional properties for eg. initResources, different types of volumes/volumeMounts
noAdditionalProperties: false

schemaRoot:
  title: FastCS Helm chart schema for services using FastCS as a subchart
  description: Schema to allow validation FastCS IOC instances
  # No additional properties in schema root for tighter protection:
  additionalProperties: false

k8sSchemaVersion: v1.33.3
