name: Package helm charts

on:
  workflow_call:

env:
  HELM_VERSION_TO_INSTALL: 3.14.3

jobs:
  package-helm-charts:
    name: Test helm chart packaging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install helm
        uses: Azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION_TO_INSTALL }}

      - name: Package helm charts
        run: |
          ./package-helm-chart.sh

      - name: Upload helm charts as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: charts
          path: charts
